version: '3'

services:
  deploy_node:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /sys:/sys #for rpi-gpio
    ports:
      - 3000:3000