version: '3'

services:
  node: #for nodejs dev envrionment
    image: node
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: sleep infinity
    env_file:
      - .env